import { Project } from '../interfaces/interfaces';

export const projects: Project[] = [
	{
		title: 'Interactive Comments',
		desc: 'This project is similar to the comment sections that are used in social media. Comments are updated in real time.',
		img: '/assets/interactivecomments.png',
		demo: 'https://interactive-comments-jb.netlify.app/',
		repository: 'https://github.com/JaacielBriseo/interactive-comments-section',
	},
	{
		title: 'IP Address Tracker',
		desc: 'The IP Address Tracker is a tool for tracking the location of any IP address or domain. It uses IP Geolocation API and Mapbox to display the location on a map.',
		img: '/assets/iptracker.jpg',
		demo: 'https://ip-address-tracker-alpha-lemon.vercel.app/',
		repository: 'https://github.com/JaacielBriseo/ip-address-tracker',
	},
	{
		title: 'Todo App',
		desc: 'To-do app with theme toggler and local storage if u want to use it for personal purpose.',
		img: '/assets/todoapp.png',
		demo: 'https://todo-app-frem.netlify.app/',
		repository: 'https://github.com/JaacielBriseo/todo-app',
	},
	{
		title: 'LoopStudios',
		desc: 'Landing page for loop studios.',
		img: '/assets/loopstudios.png',
		demo: 'https://loopstudios-dun.vercel.app/',
		repository: 'https://github.com/JaacielBriseo/loopstudios',
	},
	{
		title: 'Rock, paper, scissors',
		desc: 'Rock, paper,scissors game with animations and local storage for your score.',
		img: '/assets/rockpaper.png',
		demo: 'https://rock-paper-scissors-coral-nu.vercel.app/',
		repository: 'https://github.com/JaacielBriseo/rock-paper-scissors',
	},
	{
		title: 'Maps App',
		desc: 'GPS App where you can see your location , search for a place, add markers and trace polylines.',
		img: '/assets/mapsapp.png',
		demo: 'https://react-maps-app-jb.netlify.app/',
		repository: 'https://github.com/JaacielBriseo/maps-app',
	},
	{
		title: 'Planets Fact',
		desc: 'The Planets Fact Site is a 8-page website that provides information about different planets in our solar system.',
		img: '/assets/planetsfact.png',
		demo: 'https://planets-fact-nine.vercel.app/',
		repository: 'https://github.com/JaacielBriseo/planets-fact',
	},
	{
		title: 'Countries site',
		desc: 'With this app, users can access a comprehensive database of country information and easily navigate through it.',
		img: '/assets/countries.png',
		demo: 'https://rest-countries-api-orpin.vercel.app/',
		repository: 'https://github.com/JaacielBriseo/rest-countries-api',
	},
	{
		title: 'Bookmark landing page',
		desc: 'Landing page for a simple bookmark manager extension.',
		img: '/assets/bookmark.png',
		demo: 'https://jaacielbriseo.github.io/bookmark-page/',
		repository: 'https://github.com/JaacielBriseo/bookmark-page',
	},
	{
		title: 'Fylo landing page',
		desc: 'Landing page with dark/light mode toggler.',
		img: '/assets/fylo.png',
		demo: 'https://jaacielbriseo.github.io/fylo-landing-page/',
		repository: 'https://github.com/JaacielBriseo/fylo-landing-page',
	},
	{
		title: 'Advice generator',
		desc: 'Advice generator web app that pulls an advice from an API.',
		img: '/assets/advices.jpg',
		demo: 'https://jaacielbriseo.github.io/advice-generator/',
		repository: 'https://github.com/JaacielBriseo/advice-generator',
	},
	{
		title: 'Journal App',
		desc: 'This app provides the user an accessible storage to save memories with photos, title and description.',
		img: '/assets/journal.png',
		demo: 'https://journalappv1.netlify.app/#/auth/login',
		repository: 'https://github.com/JaacielBriseo/Journal-App',
	},
];
